stages:
  ingest:
    # Generate a synthetic Parquet file of processed features.  In a
    # production pipeline this stage would perform feature engineering on
    # raw data and write a Parquet dataset.
    cmd: python -m src.features.ingest
    deps:
      - src/features/ingest.py
    outs:
      - data/processed/features.parquet

  train:
    # Train a simple XGBoost model and log it with MLflow.  This stage
    # depends on the processed features produced by the ingest stage.
    cmd: python -m src.training.train
    deps:
      - src/training/train.py
      - data/processed/features.parquet
    outs:
      - models/model.pkl