stages:
  ingest:
    cmd: python src/features/ingest.py
    deps:
      - src/features/ingest.py
    outs:
      - data/raw/data.csv

  validate:
    cmd: python src/features/validate_data.py
    deps:
      - data/raw/data.csv
      - expectations/
    outs:
      - data/processed/validated.csv

  train:
    cmd: python src/training/train_model.py
    deps:
      - data/processed/validated.csv
      - src/training/train_model.py
    outs:
      - models/latest_model.pkl
    metrics:
      - models/metrics.json

  evaluate:
    cmd: python src/evaluation/evaluate.py
    deps:
      - models/latest_model.pkl
      - src/evaluation/evaluate.py
    outs:
      - models/evaluation.json